### PR TITLE
fixes bug 1433316 - unthrottle Firefox pre-57

### PR DESCRIPTION
**Pull request by willkg**

### CODE REVIEW

**Comment by willkg** [comment]
@lonnen Does this rule match what you were thinking?

**Comment by lonnen** [comment]
Yes. This looks correct to me. We can scale it up from there as we are sure that the load isn't an issue.

unrelated to this change, but proximal:  `# 100% of PrductName=Fennec` has a typo

**Comment by willkg** [comment]
Typo fixed!

**Comment by willkg** [comment]
Thank you!

**Pull request merged**
